### ISSUE TITLE
你好  有关于使用此框架显示动画的问题咨询

### ISSUE THREAD

**Issue by dragon1061** [chennyhuang/ptoto#1]
```
 我在使用此框架时 我的collectionView是放在tableView的第一个cell里的 但是点击collectionView出来的时候的动画没有了  想咨询一下要怎么处理
```

**Comment by chennyhuang** [comment]
不能在tableview的cell里面使用collectionview来展示图片，这种操做不适用于这个程序

**Comment by dragon1061** [comment]
谢谢你的回复 










在 2016-03-18 10:42:29，"chennyhuang" <notifications@github.com> 写道：


不能在tableview的cell里面使用collectionview来展示图片，这种操做不适用于这个程序

**Comment by zhnnnnn** [comment]
viewmode 的原因，退回动画会抖一下的。。。你在退回动画hidePhotoBrowser里面 加上设置mode的代码吧。
        tempImageView.contentMode = UIViewContentModeScaleAspectFill;
        tempImageView.clipsToBounds = YES;

**Comment by taojeff** [comment]
楼主，为什么我把你的项目集成到我的项目中后那个动态的GIF图片在小图片的时候就直接动起来了 而不是在大图的时候就开始呢

**Comment by taojeff** [comment]
还有一个问题是有时候在运行功能的时候点击查看图片会在- (void)setProgress:(CGFloat)progress
{
    _progress = progress;
    [self setNeedsDisplay];
    if (progress >= 1) {
        [self removeFromSuperview];
    }
}这个代码的if这块崩溃

**Comment by QuintGao** [comment]
你好，请问如果我想加个按钮，实现强制横屏，该怎么实现？

**Comment by xiaoer371** [comment]
@taojeff  [self removeFromSuperview];    ui 操作要调回主线程。。。
