### ISSUE TITLE
你好，想问下 你这段代码会不会 导致内存一直在增长？？

### ISSUE THREAD

**Issue by emodeqidao** [chennyhuang/ptoto#5]
HZPhotoGroup *photoGroup = [[HZPhotoGroup alloc] init];
    
    NSMutableArray *temp = [NSMutableArray array];
    [_srcStringArray enumerateObjectsUsingBlock:^(NSString *src, NSUInteger idx, BOOL *stop) {
        HZPhotoItem *item = [[HZPhotoItem alloc] init];
        item.thumbnail_pic = src;
        [temp addObject:item];
    }];
    
    photoGroup.photoItemArray = [temp copy];
    [cell.contentView addSubview:photoGroup];
在demo 里面的 HZTableViewController.m   里的方法 - (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath

**Comment by chennyhuang** [comment]
内存没有优化，这个适合9张图

**Comment by emodeqidao** [comment]
看着不对劲啊！优化下吧！ 😝

**Comment by chennyhuang** [comment]
目前不做优化，就这样，给有这种需要的图片展示提供一个思路

**Comment by emodeqidao** [comment]
😯😯😯😯😯😯😯
